package me.dablakbandit.annotateconfig;

import me.dablakbandit.annotateconfig.annotation.ConfigComment;
import me.dablakbandit.annotateconfig.annotation.ConfigIgnore;
import me.dablakbandit.annotateconfig.annotation.ConfigKey;
import me.dablakbandit.annotateconfig.annotation.ConfigMigrate;
import me.dablakbandit.annotateconfig.annotation.ConfigPath;
import me.dablakbandit.annotateconfig.annotation.ConfigRoot;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

class AnnotateConfigTest {
    @TempDir
    Path tempDir;

    @Test
    void loadMigratesWritesCommentsAndPreservesUnknownFields() throws IOException {
        TestConfig.reset();
        Path file = tempDir.resolve("config.yml");
        Files.writeString(file, String.join("\n",
            "legacy:",
            "  enabled: false",
            "custom-value: keep-me",
            "spawn:",
            "  world: world_nether",
            "  x: 10",
            "  y: 64",
            "  z: -3",
            "checkpoints:",
            "  - world: world",
            "    x: 1",
            "    y: 2",
            "    z: 3",
            "  - world: world_the_end",
            "    x: 9",
            "    y: 80",
            "    z: 4",
            "save-settings:",
            "  mode: JSON",
            ""
        ));

        ConfigHandle handle = AnnotateConfig.builder(TestConfig.class, file)
            .serializer(LocationValue.class, new LocationValueSerializer())
            .build();
        handle.load();

        assertFalse(TestConfig.enabled);
        assertEquals(SaveMode.JSON, TestConfig.SaveSettings.mode);
        assertEquals(List.of("alpha", "beta"), TestConfig.tags);
        assertEquals(new LocationValue("world_nether", 10, 64, -3), TestConfig.spawn);
        assertEquals(List.of(
            new LocationValue("world", 1, 2, 3),
            new LocationValue("world_the_end", 9, 80, 4)
        ), TestConfig.checkpoints);

        Map<String, Object> yaml = TestYaml.readMap(file);
        assertFalse(TestYaml.hasPath(yaml, "legacy"));
        assertEquals(false, TestYaml.get(yaml, "enabled"));
        assertEquals("keep-me", TestYaml.get(yaml, "custom-value"));
        assertEquals("JSON", TestYaml.get(yaml, "save-settings.mode"));
        assertEquals(List.of("alpha", "beta"), TestYaml.get(yaml, "tags"));
        assertEquals("world_nether", TestYaml.get(yaml, "spawn.world"));
        assertEquals(10, TestYaml.get(yaml, "spawn.x"));

        List<String> lines = TestYaml.readLines(file);
        assertTrue(lines.stream().anyMatch(line -> line.equals("# Generated by AnnotateConfig")));
        assertTrue(lines.stream().anyMatch(line -> line.equals("# Whether the feature is enabled")));
        assertTrue(lines.stream().anyMatch(line -> line.equals("# Save backend settings")));
    }

    @Test
    void saveWritesDefaultsForNewFiles() throws IOException {
        TestConfig.reset();
        Path file = tempDir.resolve("defaults.yml");

        ConfigHandle handle = AnnotateConfig.builder(TestConfig.class, file)
            .serializer(LocationValue.class, new LocationValueSerializer())
            .build();
        handle.save();

        Map<String, Object> yaml = TestYaml.readMap(file);
        assertEquals(true, TestYaml.get(yaml, "enabled"));
        assertEquals(3, TestYaml.get(yaml, "max-retries"));
        assertEquals(List.of("alpha", "beta"), TestYaml.get(yaml, "tags"));
        assertEquals("world", TestYaml.get(yaml, "spawn.world"));
        assertEquals("YAML", TestYaml.get(yaml, "save-settings.mode"));
    }

    @Test
    void preservesUnknownFieldsWhenEnabledAndDropsWhenDisabled() throws IOException {
        PreserveConfig.reset();
        Path file = tempDir.resolve("preserve.yml");
        Files.writeString(file, String.join("\n",
            "known: 2",
            "unknown-key: keep",
            ""
        ));

        AnnotateConfig.builder(PreserveConfig.class, file)
            .preserveUnknownFields(true)
            .build()
            .load();
        Map<String, Object> kept = TestYaml.readMap(file);
        assertEquals("keep", kept.get("unknown-key"));

        PreserveConfig.reset();
        AnnotateConfig.builder(PreserveConfig.class, file)
            .preserveUnknownFields(false)
            .build()
            .load();
        Map<String, Object> dropped = TestYaml.readMap(file);
        assertFalse(dropped.containsKey("unknown-key"));
        assertEquals(2, dropped.get("known"));
    }

    @Test
    void supportsConfigPathConfigIgnoreAndConfigKey() throws IOException {
        AnnotationConfig.reset();
        Path file = tempDir.resolve("annotation.yml");
        Files.writeString(file, String.join("\n",
            "visible-value: 11",
            "hidden-value: 88",
            "custom:",
            "  absolute:",
            "    path: 42",
            "section-key:",
            "  nested-value: 77",
            "  hidden-nested: 99",
            "ignored-section:",
            "  should-not-bind: 123",
            ""
        ));

        AnnotateConfig.builder(AnnotationConfig.class, file)
            .preserveUnknownFields(false)
            .build()
            .load();

        assertEquals(11, AnnotationConfig.visibleValue);
        assertEquals(5, AnnotationConfig.hiddenValue);
        assertEquals(42, AnnotationConfig.absolutePathValue);
        assertEquals(77, AnnotationConfig.Section.nestedValue);
        assertEquals(9, AnnotationConfig.Section.hiddenNested);
        assertEquals(10, AnnotationConfig.IgnoredSection.shouldNotBind);

        Map<String, Object> written = TestYaml.readMap(file);
        assertFalse(written.containsKey("hidden-value"));
        assertFalse(TestYaml.hasPath(written, "section-key.hidden-nested"));
        assertFalse(written.containsKey("ignored-section"));
        assertEquals(42, TestYaml.get(written, "custom.absolute.path"));
    }

    @Test
    void migratesNestedRelativePaths() throws IOException {
        MigrationConfig.reset();
        Path file = tempDir.resolve("migration.yml");
        Files.writeString(file, String.join("\n",
            "inner:",
            "  old-value: 31",
            ""
        ));

        ConfigHandle handle = ConfigHandle.of(MigrationConfig.class, file);
        handle.load();

        assertEquals(31, MigrationConfig.Inner.newValue);
        Map<String, Object> written = TestYaml.readMap(file);
        assertFalse(TestYaml.hasPath(written, "inner.old-value"));
        assertEquals(31, TestYaml.get(written, "inner.new-value"));
    }

    @Test
    void appliesNamingStrategies() throws IOException {
        ExactNamingConfig.reset();
        Path exactFile = tempDir.resolve("exact.yml");
        AnnotateConfig.builder(ExactNamingConfig.class, exactFile)
            .namingStrategy(NamingStrategy.EXACT)
            .build()
            .save();
        Map<String, Object> exact = TestYaml.readMap(exactFile);
        assertEquals(7, exact.get("camelCaseField"));

        DotNamingConfig.reset();
        Path dotFile = tempDir.resolve("dot.yml");
        AnnotateConfig.builder(DotNamingConfig.class, dotFile)
            .namingStrategy(NamingStrategy.LOWER_DOT_CASE)
            .build()
            .save();
        Map<String, Object> dot = TestYaml.readMap(dotFile);
        assertEquals(9, TestYaml.get(dot, "camel.case.field"));
    }

    @Test
    void convertsSetMapAndPrimitiveTypesOnLoad() throws IOException {
        ConversionConfig.reset();
        Path file = tempDir.resolve("conversion.yml");
        Files.writeString(file, String.join("\n",
            "numbers:",
            "  - 1",
            "  - 2",
            "  - 2",
            "limits:",
            "  alpha: 5",
            "  beta: 7",
            "marker: Q",
            "enabled: true",
            ""
        ));

        ConfigHandle.of(ConversionConfig.class, file).load();

        assertEquals(new LinkedHashSet<>(Set.of(1, 2)), ConversionConfig.numbers);
        assertEquals(Map.of("alpha", 5, "beta", 7), ConversionConfig.limits);
        assertEquals('Q', ConversionConfig.marker);
        assertTrue(ConversionConfig.enabled);
    }

    @Test
    void supportsAssignableCustomSerializerLookup() throws IOException {
        AssignableSerializerConfig.reset();
        Path file = tempDir.resolve("assignable.yml");

        AnnotateConfig.builder(AssignableSerializerConfig.class, file)
            .serializer(PointLike.class, new PointLikeSerializer())
            .build()
            .save();

        Map<String, Object> written = TestYaml.readMap(file);
        assertEquals(3, TestYaml.get(written, "point.x"));
        assertEquals(4, TestYaml.get(written, "point.y"));

        Files.writeString(file, String.join("\n",
            "point:",
            "  x: 8",
            "  y: 9",
            ""
        ));

        AssignableSerializerConfig.point = new PointImpl(0, 0);
        AnnotateConfig.builder(AssignableSerializerConfig.class, file)
            .serializer(PointLike.class, new PointLikeSerializer())
            .build()
            .load();

        assertEquals(new PointImpl(8, 9), AssignableSerializerConfig.point);
    }

    @Test
    void throwsForFinalConfigField() {
        Path file = tempDir.resolve("invalid.yml");
        assertThrows(IllegalArgumentException.class, () -> AnnotateConfig.builder(InvalidFinalConfig.class, file).build());
    }

    @Test
    void throwsWhenYamlRootIsNotMap() throws IOException {
        PreserveConfig.reset();
        Path file = tempDir.resolve("invalid-root.yml");
        Files.writeString(file, "- item\n");

        ConfigHandle handle = ConfigHandle.of(PreserveConfig.class, file);
        assertThrows(IllegalArgumentException.class, handle::load);
    }

    @ConfigRoot(
        header = {"Generated by AnnotateConfig", "Safe to shade and relocate into plugins"},
        naming = NamingStrategy.LOWER_KEBAB_CASE,
        preserveUnknownFields = true
    )
    static final class TestConfig {
        @ConfigComment("Whether the feature is enabled")
        @ConfigMigrate("legacy.enabled")
        static boolean enabled = true;

        @ConfigComment("How many retries to attempt before failing")
        static int maxRetries = 3;

        @ConfigComment("Example list support")
        static List<String> tags = new ArrayList<>(List.of("alpha", "beta"));

        @ConfigComment("Serialized custom value")
        static LocationValue spawn = new LocationValue("world", 0, 64, 0);

        @ConfigComment("Serialized custom values inside a list")
        static List<LocationValue> checkpoints = new ArrayList<>(List.of(
            new LocationValue("world", 2, 70, 2),
            new LocationValue("world", 4, 72, 4)
        ));

        @ConfigComment("Save backend settings")
        static final class SaveSettings {
            @ConfigComment("Storage mode to use")
            static SaveMode mode = SaveMode.YAML;

            @ConfigKey("connection-pool-size")
            static int poolSize = 4;
        }

        static void reset() {
            enabled = true;
            maxRetries = 3;
            tags = new ArrayList<>(List.of("alpha", "beta"));
            spawn = new LocationValue("world", 0, 64, 0);
            checkpoints = new ArrayList<>(List.of(
                new LocationValue("world", 2, 70, 2),
                new LocationValue("world", 4, 72, 4)
            ));
            SaveSettings.mode = SaveMode.YAML;
            SaveSettings.poolSize = 4;
        }
    }

    @ConfigRoot(preserveUnknownFields = false)
    static final class PreserveConfig {
        static int known = 1;

        static void reset() {
            known = 1;
        }
    }

    @ConfigRoot
    static final class AnnotationConfig {
        static int visibleValue = 1;

        @ConfigIgnore
        static int hiddenValue = 5;

        @ConfigPath("custom.absolute.path")
        static int absolutePathValue = 0;

        @ConfigIgnore
        static final class IgnoredSection {
            static int shouldNotBind = 10;
        }

        @ConfigKey("section-key")
        static final class Section {
            static int nestedValue = 1;

            @ConfigIgnore
            static int hiddenNested = 9;
        }

        static void reset() {
            visibleValue = 1;
            hiddenValue = 5;
            absolutePathValue = 0;
            IgnoredSection.shouldNotBind = 10;
            Section.nestedValue = 1;
            Section.hiddenNested = 9;
        }
    }

    @ConfigRoot
    static final class MigrationConfig {
        @ConfigComment("migration")
        static final class Inner {
            @ConfigMigrate("old-value")
            static int newValue = 4;
        }

        static void reset() {
            Inner.newValue = 4;
        }
    }

    static final class ExactNamingConfig {
        static int camelCaseField = 7;

        static void reset() {
            camelCaseField = 7;
        }
    }

    static final class DotNamingConfig {
        static int camelCaseField = 9;

        static void reset() {
            camelCaseField = 9;
        }
    }

    @ConfigRoot
    static final class ConversionConfig {
        static Set<Integer> numbers = new LinkedHashSet<>();
        static Map<String, Integer> limits = new LinkedHashMap<>();
        static char marker = 'A';
        static boolean enabled = false;

        static void reset() {
            numbers = new LinkedHashSet<>();
            limits = new LinkedHashMap<>();
            marker = 'A';
            enabled = false;
        }
    }

    @ConfigRoot
    static final class AssignableSerializerConfig {
        static PointImpl point = new PointImpl(3, 4);

        static void reset() {
            point = new PointImpl(3, 4);
        }
    }

    @ConfigRoot
    static final class InvalidFinalConfig {
        static final int bad = 1;
    }

    interface PointLike {
        int x();

        int y();
    }

    record PointImpl(int x, int y) implements PointLike {
    }

    static final class PointLikeSerializer implements ConfigSerializer<PointLike> {
        @Override
        public Object serialize(PointLike value) {
            Map<String, Object> serialized = new LinkedHashMap<>();
            serialized.put("x", value.x());
            serialized.put("y", value.y());
            return serialized;
        }

        @Override
        public PointLike deserialize(Object raw) {
            @SuppressWarnings("unchecked")
            Map<String, Object> map = (Map<String, Object>) raw;
            return new PointImpl(((Number) map.get("x")).intValue(), ((Number) map.get("y")).intValue());
        }
    }

    record LocationValue(String world, int x, int y, int z) {
    }

    static final class LocationValueSerializer implements ConfigSerializer<LocationValue> {
        @Override
        public Object serialize(LocationValue value) {
            Map<String, Object> serialized = new LinkedHashMap<>();
            serialized.put("world", value.world());
            serialized.put("x", value.x());
            serialized.put("y", value.y());
            serialized.put("z", value.z());
            return serialized;
        }

        @Override
        public LocationValue deserialize(Object raw) {
            @SuppressWarnings("unchecked")
            Map<String, Object> values = (Map<String, Object>) raw;
            return new LocationValue(
                String.valueOf(values.get("world")),
                ((Number) values.get("x")).intValue(),
                ((Number) values.get("y")).intValue(),
                ((Number) values.get("z")).intValue()
            );
        }
    }

    enum SaveMode {
        YAML,
        JSON
    }
}
